"use client";

import dynamic from "next/dynamic";

export const examples = {
  "reveal": dynamic(() => import("./reveal")),
  "stagger": dynamic(() => import("./stagger")),
  "sequential-content": dynamic(() => import("./sequential-content")),
  "animated-list": dynamic(() => import("./animated-list")),
  "shared-element": dynamic(() => import("./shared-element")),
  "shared-indicator": dynamic(() => import("./shared-indicator")),
  "auto-height": dynamic(() => import("./auto-height")),
  "layout-shift": dynamic(() => import("./layout-shift")),
  "pressable": dynamic(() => import("./pressable")),
  "async-button": dynamic(() => import("./async-button")),
  "icon-swap-button": dynamic(() => import("./icon-swap-button")),
  "copy-button": dynamic(() => import("./copy-button")),
  "shake": dynamic(() => import("./shake")),
  "toggle-motion": dynamic(() => import("./toggle-motion")),
  "checkbox-motion": dynamic(() => import("./checkbox-motion")),
  "spinner": dynamic(() => import("./spinner")),
  "dots-loader": dynamic(() => import("./dots-loader")),
  "pulse-loader": dynamic(() => import("./pulse-loader")),
  "skeleton": dynamic(() => import("./skeleton")),
  "shimmer": dynamic(() => import("./shimmer")),
  "progress-bar": dynamic(() => import("./progress-bar")),
  "circular-progress": dynamic(() => import("./circular-progress")),
  "loading-swap": dynamic(() => import("./loading-swap")),
  "page-transition": dynamic(() => import("./page-transition")),
  "scroll-reveal": dynamic(() => import("./scroll-reveal")),
  "scroll-progress": dynamic(() => import("./scroll-progress")),
  "backdrop": dynamic(() => import("./backdrop")),
  "modal-motion": dynamic(() => import("./modal-motion")),
  "drawer-motion": dynamic(() => import("./drawer-motion")),
  "popover-motion": dynamic(() => import("./popover-motion")),
  "dropdown-motion": dynamic(() => import("./dropdown-motion")),
  "toast-motion": dynamic(() => import("./toast-motion")),
  "loading-overlay": dynamic(() => import("./loading-overlay")),
};
